apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: vector-generator-hpa
  namespace: default
spec:
  scaleTargetRef:
    name: vector-generator
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: my-cluster-kafka-bootstrap.default:9092
      consumerGroup: my-consumer-group
      topic: my-topic
      lagThreshold: "500000"
